import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const packageJsonPath = path.resolve(import.meta.dir, "..", "package.json");
const outputPath = path.resolve(
  import.meta.dir,
  "..",
  "src",
  "generated",
  "version.ts",
);

const packageJson = JSON.parse(await readFile(packageJsonPath, "utf8")) as {
  version?: string;
};

if (!packageJson.version) {
  throw new Error("Missing package version");
}

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  [
    "// This file is generated by scripts/sync-version.ts.",
    `export const version = ${JSON.stringify(packageJson.version)};`,
    "",
  ].join("\n"),
);
