export const DOC_CATEGORIES = [
  {
    id: "actions",
    title: "Actions",
    description: "Controls that trigger commands or workflows.",
  },
  {
    id: "layout",
    title: "Layout",
    description: "Primitives for arranging content and page structure.",
  },
  {
    id: "navigation",
    title: "Navigation",
    description: "Controls that move through pages and content.",
  },
  {
    id: "data-entry",
    title: "Data Entry",
    description: "Controls for collecting and changing values.",
  },
  {
    id: "data-display",
    title: "Data Display",
    description: "Components for presenting content and records.",
  },
  {
    id: "feedback",
    title: "Feedback",
    description: "Status, progress, alerts, and confirmation patterns.",
  },
  {
    id: "surfaces",
    title: "Surfaces",
    description: "Containers and overlays for grouping content.",
  },
  {
    id: "css-art",
    title: "CSS Art",
    description: "Illustrative scenes and animated CSS art.",
  },
  {
    id: "theming",
    title: "Theming & Configuration",
    description: "Theme and configuration APIs for DuskMoon apps.",
  },
  {
    id: "utilities",
    title: "Utilities & Types",
    description: "Helpers, hooks, types, and package utilities.",
  },
] as const;

export type DocCategoryId = (typeof DOC_CATEGORIES)[number]["id"];

const targetCategories: Record<string, DocCategoryId> = {
  button: "actions",
  "float-button": "actions",
  fab: "actions",
  swap: "actions",
  dropdown: "actions",
  "dm-toolbar": "actions",

  col: "layout",
  flex: "layout",
  grid: "layout",
  layout: "layout",
  "console-page": "layout",
  row: "layout",
  space: "layout",
  splitter: "layout",
  divider: "layout",
  "dm-layout": "layout",
  "dm-splitter": "layout",
  "dm-page-header": "layout",

  affix: "navigation",
  anchor: "navigation",
  "back-top": "navigation",
  breadcrumb: "navigation",
  menu: "navigation",
  megamenu: "navigation",
  pagination: "navigation",
  steps: "navigation",
  tabs: "navigation",
  "dm-breadcrumb": "navigation",
  "dm-menu": "navigation",
  "dm-pagination": "navigation",
  "dm-tabs": "navigation",

  "auto-complete": "data-entry",
  cascader: "data-entry",
  checkbox: "data-entry",
  "color-picker": "data-entry",
  "date-picker": "data-entry",
  form: "data-entry",
  input: "data-entry",
  "otp-input": "data-entry",
  "input-number": "data-entry",
  mentions: "data-entry",
  radio: "data-entry",
  rate: "data-entry",
  segmented: "data-entry",
  select: "data-entry",
  slider: "data-entry",
  switch: "data-entry",
  "time-picker": "data-entry",
  "tree-select": "data-entry",
  upload: "data-entry",
  transfer: "data-entry",
  "dm-date-picker": "data-entry",
  "dm-query": "data-entry",
  "dm-search": "data-entry",

  avatar: "data-display",
  badge: "data-display",
  calendar: "data-display",
  carousel: "data-display",
  chat: "data-display",
  descriptions: "data-display",
  image: "data-display",
  list: "data-display",
  markdown: "data-display",
  "qr-code": "data-display",
  statistic: "data-display",
  table: "data-display",
  tag: "data-display",
  timeline: "data-display",
  tree: "data-display",
  typography: "data-display",
  watermark: "data-display",
  "dm-infinite-scroll": "data-display",
  "dm-pro-table": "data-display",
  "dm-status": "data-display",
  "dm-table": "data-display",
  "dm-tree": "data-display",
  "dm-truncate": "data-display",

  alert: "feedback",
  message: "feedback",
  notification: "feedback",
  popconfirm: "feedback",
  tour: "feedback",
  empty: "feedback",
  progress: "feedback",
  result: "feedback",
  skeleton: "feedback",
  spin: "feedback",
  "dm-message": "feedback",

  card: "surfaces",
  collapse: "surfaces",
  drawer: "surfaces",
  modal: "surfaces",
  popover: "surfaces",
  tooltip: "surfaces",
  "dm-auxiliary": "surfaces",
  "dm-drawer": "surfaces",

  app: "theming",
  "config-provider": "theming",
  "dm-provider": "theming",
  theme: "theming",
  "get-dm-theme": "theming",
  "on-dm-theme-update": "theming",
  "set-dm-prefix-cls": "theming",
  "set-dm-primary-color": "theming",
  "set-dm-date-picker-locale": "theming",

  version: "utilities",
  "unstable-set-render": "utilities",
  "get-props": "utilities",
  "get-ref": "utilities",
  "get-prop": "utilities",
  breakpoint: "utilities",
  "use-persisted-page-size": "utilities",
};

export function categoryForTarget({ id, kind }: { id: string; kind: string }) {
  if (kind === "art-component") return "css-art";

  if (Object.hasOwn(targetCategories, id)) return targetCategories[id];

  throw new Error(
    `Unknown documentation classification for target "${id}" (kind: "${kind}"). Add it to docs-categories.ts.`,
  );
}
